# Generated by Django 3.1.3 on 2020-11-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Hour',
        ),
        migrations.RenameField(
            model_name='hour',
            old_name='lst',
            new_name='name',
        ),
    ]
